require('dotenv').config();
const nodemailer = require('nodemailer');

(async () => {
  const user = process.env.EMAIL_USER;
  const pass = process.env.EMAIL_PASSWORD;
  if (!user || !pass) {
    console.error('Set EMAIL_USER and EMAIL_PASSWORD in .env before running this test.');
    process.exit(1);
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: { user, pass },
  });

  try {
    console.log('Verifying SMTP configuration...');
    await transporter.verify();
    console.log('SMTP verified OK');

    const info = await transporter.sendMail({
      from: `"Website Test" <${user}>`,
      to: user,
      subject: 'SMTP test from Website-Blockchain',
      text: 'This is a test email generated by test-smtp.js'
    });

    console.log('Test email sent:', info.messageId || info.response || info);
    process.exit(0);
  } catch (err) {
    console.error('SMTP error:', err);
    process.exit(2);
  }
})();
